version: '3.9'

services:
  db:
    image: postgres:16.4-alpine
    container_name: postgres-n8n
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://localhost:5432/n8n

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    ports:
      - '11434:11434'
    volumes:
      - ./model_files:/model_files
    tty: true

  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - '5678:5678'
    volumes:
      - ./n8n-data:/home/node/.n8n

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    profiles:
      - local
